### ISSUE TITLE
[Meta] MPC specification

### ISSUE THREAD

**Issue by jschneider-bensch** [cryspen/atlas#47]
- [x] Outline architecture (#46)
- [x] Specify circuit representation (#42)
- [ ] Specify primtitives
  - [x] #48
  - [x] #49
  - [ ] #63 
- [x] Specify Preprocessing phases
  - [x] #50
  - [x] #51
- [x] Specify online phases
  - [x] #52
  - [x] #54
  - [x] #53

**Comment by franziskuskiefer** [comment]
@jschneider-bensch can this be closed? If not, please update.

**Comment by jschneider-bensch** [comment]
We have yet to implement an actively secure version of the two-party bit authentication, which essentially consists of an actively secure correlated OT extension, cf. #63.

**Comment by jschneider-bensch** [comment]
Moving the deadline to the end of the year on this, since we might make use of it for automated checks.

**Comment by franziskuskiefer** [comment]
@jschneider-bensch shall we close this?

**Comment by jschneider-bensch** [comment]
Indeed, I will close the remaining issues as not planned. We may re-open some of them in the context of https://github.com/cryspen/home/issues/78 which I'll leave open.
